[tasks.install]

	description = "Installs torset in /usr/local/bin."

	script = [

		"cargo build --release",

		"echo Installing in /usr/local/bin",

		"sudo mkdir --parents /usr/local/bin",
		"sudo cp    --force target/release/torset /usr/local/bin",
		"sudo chmod 755 /usr/local/bin/torset",
		"sudo mkdir --parents /usr/local/share/man/man1",
		"sudo cp    --force doc/torset.1 /usr/local/share/man/man1/",
		"sudo gzip  --force /usr/local/share/man/man1/torset.1",
	]


[tasks.remove]

	alias = "uninstall"


[tasks.uninstall]

	description = "Installs torset in /usr/local/bin."

	script = [

		"sudo rm -f /usr/local/bin/torset",
		"sudo rm -f /usr/local/share/man/man1/torset.1.gz",
	]
